### ISSUE TITLE
resolve duplicates in datasets.json

### ISSUE THREAD

**Issue by srand525** [Coleridge-Initiative/RCDatasets#145]
ID and resolve dupes in datasets.json. E.g dataset-160, ES-202 Files, may be a dupe of other employment/wage datasets

There are others as well that I've come across - searching across alt_titles is one approach to finding them

**Comment by ceteri** [comment]
The only other dataset which appears to have overlap would be `dataset-328` since it also includes `ES-202` data.  However, one is state level (Mass) while the other is federal (BLS).
