### ISSUE TITLE
dataset-678 seems to have wrong provider ID

### ISSUE THREAD

**Issue by lobodemonte** [Coleridge-Initiative/RCDatasets#168]
Provider-067 is mapped to Google, but dataset-678 seems to come from provider US Geological Survey (provider-236)

{
        "id": "dataset-678",
        "provider": "provider-067",
        "title": "Landsat data",
        "url": "https://earthexplorer.usgs.gov/"
},

**Comment by menoah** [comment]
Gotcha, I'll update the dataset during my next PR
