### ISSUE TITLE
Dataset scope fixes 

### ISSUE THREAD

**Issue by ernestogimeno** [Coleridge-Initiative/RCDatasets#238]
We got feedback gathered while working with task [Cross-link ADRF dataset identifiers ](https://github.com/Coleridge-Initiative/RCDatasets/issues/207). Some changes are required in datasets.json:

- Dataset-141: merge it with dataset-118, and add a comment to document the decision (unify all decennial censuses into one dataset). Apply also to partitions.
- Dataset-366 and dataset-367: remove reference to Illinois and add a comment to document the decision (using a federal scope).

**Comment by ernestogimeno** [comment]
Dataset-141 was not found in any partition of RCPublications

**Comment by ceteri** [comment]
Great, thanks for checking that through
